# Generated by Django 5.2.6 on 2025-10-01 05:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('stock', models.PositiveIntegerField(default=0)),
                ('condition', models.CharField(choices=[('baru', 'Baru'), ('bekas', 'Bekas')], default='baru', max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('update', 'Update'), ('sepatu', 'Sepatu'), ('topi', 'Topi'), ('celana', 'Celana'), ('botol minum', 'Botol Minum'), ('bola', 'Bola')], default='jersey', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
