# Generated by Django 5.2.6 on 2025-09-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_shop_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stok',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
