# Generated by Django 5.2.6 on 2025-09-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_stok'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stok',
            new_name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('baru', 'Baru'), ('bekas', 'Bekas')], default='baru', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jersey', 'Jersey'), ('update', 'Update'), ('sepatu', 'Sepatu'), ('topi', 'Topi'), ('celana', 'Celana'), ('botol minum', 'Botol Minum')], default='jersey', max_length=20),
        ),
    ]
