# Generated by Django 5.2.6 on 2025-09-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jersey', 'Jersey'), ('update', 'Update'), ('sepatu', 'Sepatu'), ('topi', 'Topi'), ('celana', 'Celana'), ('botol minum', 'Botol Minum'), ('bola', 'Bola')], default='jersey', max_length=20),
        ),
    ]
